name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Initialize EAS project
        run: |
          echo "Initializing EAS project..."
          eas init --id d328c24c-b79b-4dda-a2f1-b95d66100a2d --non-interactive || echo "Already initialized"
          
      - name: Build APK
        run: eas build --platform android --profile production --non-interactive
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: "*.apk"

